tap "caskroom/cask"

brew "bash"
brew "git"
brew "gnupg"
brew "pinentry-mac"
brew "direnv"

cask "google-chrome"
cask "vlc"
cask "alfred"
cask "caffeine"
cask "spectacle"
cask "flux"
cask "caskroom/versions/java8"
cask "intellij-idea"
cask "firefox"
cask "postman"
cask "gpg-suite"
